In [2]:
import pandas as pd
import numpy as np

In [3]:
sam_adds = pd.read_csv("Geolocated_SAMAddresses.csv")

C:\Users\adity\AppData\Local\Temp\ipykernel_106372\1067669544.py:1: DtypeWarning: Columns (7,9,10,18,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  sam_adds = pd.read_csv("Geolocated_SAMAddresses.csv")

In [4]:
sam_adds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400197 entries, 0 to 400196
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   X                     400197 non-null  float64
 1   Y                     400197 non-null  float64
 2   OBJECTID              400197 non-null  int64
 3   SAM_ADDRESS_ID        400197 non-null  int64
 4   BUILDING_ID           400197 non-null  int64
 5   RELATIONSHIP_TYPE     400197 non-null  int64
 6   FULL_ADDRESS          400197 non-null  object
 7   STREET_NUMBER         400197 non-null  object
 8   IS_RANGE              400197 non-null  int64
 9   RANGE_FROM            25926 non-null   object
 10  RANGE_TO              25926 non-null   object
 11  UNIT                  268565 non-null  object
 12  FULL_STREET_NAME      400189 non-null  object
 13  STREET_ID             400193 non-null  float64
 14  STREET_PREFIX         21391 non-null   object
 15  STREET_BODY           400189 non-null  object
 16  STREET_SUFFIX_ABBR    396113 non-null  object
 17  STREET_FULL_SUFFIX    396113 non-null  object
 18  STREET_SUFFIX_DIR     1009 non-null    object
 19  STREET_NUMBER_SORT    400197 non-null  int64
 20  MAILING_NEIGHBORHOOD  400197 non-null  object
 21  ZIP_CODE              400197 non-null  int64
 22  X_COORD               400197 non-null  float64
 23  Y_COORD               400197 non-null  float64
 24  SAM_STREET_ID         400193 non-null  float64
 25  WARD                  400197 non-null  int64
 26  PRECINCT_WARD         400197 non-null  int64
 27  PARCEL                400197 non-null  object
 28  created_date          243000 non-null  object
 29  last_edited_date      335844 non-null  object
 30  Latitude              396042 non-null  float64
 31  Longitude             396042 non-null  float64
dtypes: float64(8), int64(9), object(15)
memory usage: 97.7+ MB

In [5]:
n_zip = pd.read_csv("Updated_Zip_Code_and_Neighborhood_Mapping.csv")
n_zip['Zip Code'] = n_zip['Zip Code'].astype(str)
n_zip['Zip Code'] = n_zip['Zip Code'].apply(lambda x: '0'+x)

In [6]:
sam_adds['ZIP_CODE'] = sam_adds['ZIP_CODE'].astype(str)
sam_adds['ZIP_CODE'] = sam_adds['ZIP_CODE'].apply(lambda x: "0"+x)

In [7]:
sam_adds = pd.merge(sam_adds,n_zip, left_on='ZIP_CODE', right_on='Zip Code', how='left')

In [8]:
sam_adds_bldgs = sam_adds[['BUILDING_ID','Zip Code','Neighbourhood']]
sam_adds_bldgs = sam_adds_bldgs.drop_duplicates()

In [9]:
no_of_bldgs = sam_adds_bldgs.groupby(['Neighbourhood']).size()

In [10]:
no_of_bldgs =no_of_bldgs.reset_index()
no_of_bldgs.columns = ['Neighbourhood','no_of_bldgs']

In [11]:
no_of_bldgs.sort_values(by='no_of_bldgs', ascending=False, inplace=True)

In [12]:
no_of_bldgs.head()

   Neighbourhood  no_of_bldgs
7     Dorchester        17587
17       Roxbury         8825
21  West Roxbury         8478
11     Hyde Park         7700
16    Roslindale         6717

In [19]:
student_sam = pd.read_csv('Final_dataset.csv')

C:\Users\adity\AppData\Local\Temp\ipykernel_106372\579174025.py:1: DtypeWarning: Columns (0,4,5,7,8,32,41,44,45) have mixed types. Specify dtype option on import or set low_memory=False.
  student_sam = pd.read_csv('Final_dataset.csv')

In [20]:
student_sam['Neighbourhood']

0              Allston
1              Allston
2              Allston
3              Allston
4              Allston
              ...
353892      Dorchester
353893      Dorchester
353894       South End
353895    Mission Hill
353896         Roxbury
Name: Neighbourhood, Length: 353897, dtype: object

In [21]:
len(student_sam.sam_id.unique())

3120

In [24]:
no_of_bldgs_student=student_sam[['Neighbourhood','sam_id']].drop_duplicates('sam_id').groupby('Neighbourhood').size()

In [31]:
no_of_bldgs_student=no_of_bldgs_student.reset_index()
no_of_bldgs_student.columns = ['Neighbourhood','no_of_bldgs_student']

In [32]:
no_of_bldgs_student

              Neighbourhood  no_of_bldgs_student
0                   Allston                  203
1                  Back Bay                  141
2               Beacon Hill                   36
3                  Brighton                  233
4               Charlestown                   57
5                 Chinatown                   32
6                Dorchester                  555
7                  Downtown                  140
8               East Boston                  312
9            Fenway/Kenmore                  153
10                Hyde Park                  102
11            Jamaica Plain                  117
12                 Mattapan                  102
13             Mission Hill                  129
14                North End                  115
15               Roslindale                   58
16                  Roxbury                  309
17             South Boston                  155
18  South Boston Waterfront                    6
19                South End                  120
20             West Roxbury                   42

In [33]:
no_of_bldgs = pd.merge(no_of_bldgs, no_of_bldgs_student, on='Neighbourhood', how='left')

In [35]:
no_of_bldgs.dropna(inplace=True)

In [36]:
no_of_bldgs['%_bldgs_occupied_by_students'] = no_of_bldgs['no_of_bldgs_student']*100/no_of_bldgs['no_of_bldgs']

In [37]:
no_of_bldgs

,Neighbourhood,no_of_bldgs,no_of_bldgs_student,%_bldgs_occupied_by_students
0,Dorchester,17587,555.0,3.155740
1,Roxbury,8825,309.0,3.501416
2,West Roxbury,8478,42.0,0.495400
3,Hyde Park,7700,102.0,1.324675
4,Roslindale,6717,58.0,0.863481
5,Jamaica Plain,6149,117.0,1.902748
6,East Boston,6062,312.0,5.146816
7,South Boston,5959,155.0,2.601108
8,Brighton,5310,233.0,4.387947
9,Mattapan,4154,102.0,2.455465
10,Charlestown,2795,57.0,2.039356
11,South End,2371,120.0,5.061156
12,Back Bay,2102,141.0,6.707897
13,Allston,2077,203.0,9.773712
14,Fenway/Kenmore,1959,153.0,7.810107
15,Downtown,1449,140.0,9.661836
16,Mission Hill,1297,129.0,9.946029
17,North End,825,115.0,13.939394
18,Beacon Hill,652,36.0,5.521472
19,Chinatown,336,32.0,9.523810
20,South Boston Waterfront,278,6.0,2.158273

In [42]:
no_of_bldgs=pd.melt(
    no_of_bldgs,
    id_vars=["Neighbourhood", "%_bldgs_occupied_by_students"],
    value_vars=["no_of_bldgs_student", "no_of_bldgs"],
    var_name="Building Type",
    value_name="Count"
)

In [43]:
no_of_bldgs

,Neighbourhood,%_bldgs_occupied_by_students,Building Type,Count
0,Dorchester,3.155740,no_of_bldgs_student,555.0
1,Roxbury,3.501416,no_of_bldgs_student,309.0
2,West Roxbury,0.495400,no_of_bldgs_student,42.0
3,Hyde Park,1.324675,no_of_bldgs_student,102.0
4,Roslindale,0.863481,no_of_bldgs_student,58.0
5,Jamaica Plain,1.902748,no_of_bldgs_student,117.0
6,East Boston,5.146816,no_of_bldgs_student,312.0
7,South Boston,2.601108,no_of_bldgs_student,155.0
8,Brighton,4.387947,no_of_bldgs_student,233.0
9,Mattapan,2.455465,no_of_bldgs_student,102.0
10,Charlestown,2.039356,no_of_bldgs_student,57.0
11,South End,5.061156,no_of_bldgs_student,120.0
12,Back Bay,6.707897,no_of_bldgs_student,141.0
13,Allston,9.773712,no_of_bldgs_student,203.0
14,Fenway/Kenmore,7.810107,no_of_bldgs_student,153.0
15,Downtown,9.661836,no_of_bldgs_student,140.0
16,Mission Hill,9.946029,no_of_bldgs_student,129.0
17,North End,13.939394,no_of_bldgs_student,115.0
18,Beacon Hill,5.521472,no_of_bldgs_student,36.0
19,Chinatown,9.523810,no_of_bldgs_student,32.0
20,South Boston Waterfront,2.158273,no_of_bldgs_student,6.0
21,Dorchester,3.155740,no_of_bldgs,17587.0
22,Roxbury,3.501416,no_of_bldgs,8825.0
23,West Roxbury,0.495400,no_of_bldgs,8478.0
24,Hyde Park,1.324675,no_of_bldgs,7700.0
25,Roslindale,0.863481,no_of_bldgs,6717.0
26,Jamaica Plain,1.902748,no_of_bldgs,6149.0
27,East Boston,5.146816,no_of_bldgs,6062.0
28,South Boston,2.601108,no_of_bldgs,5959.0
29,Brighton,4.387947,no_of_bldgs,5310.0
30,Mattapan,2.455465,no_of_bldgs,4154.0
31,Charlestown,2.039356,no_of_bldgs,2795.0
32,South End,5.061156,no_of_bldgs,2371.0
33,Back Bay,6.707897,no_of_bldgs,2102.0
34,Allston,9.773712,no_of_bldgs,2077.0
35,Fenway/Kenmore,7.810107,no_of_bldgs,1959.0
36,Downtown,9.661836,no_of_bldgs,1449.0
37,Mission Hill,9.946029,no_of_bldgs,1297.0
38,North End,13.939394,no_of_bldgs,825.0
39,Beacon Hill,5.521472,no_of_bldgs,652.0
40,Chinatown,9.523810,no_of_bldgs,336.0
41,South Boston Waterfront,2.158273,no_of_bldgs,278.0

In [44]:
no_of_bldgs.to_csv('No_of_bldgs.csv',index=False)

[View the visualizations here](https://lookerstudio.google.com/reporting/04a5b8cc-d28a-4b61-b088-10d7c92ea456)